name: ci
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16']
    steps:
      - name: récupération du repository
        uses: actions/checkout@v3
      - name: installation de node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: installation des dépendances
        run: npm i
      - name: tests unitaires
        run: npm run test
      - name: coverage
        run: npm run cover
      - name: récupération des résultats de tests
        uses: actions/upload-artifact@v3
        with:
          name: result-test
          path: ./reports